name: Simple Parallel Workflow

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
        - name: Run Linting
          run: echo "Running linter..."

    test:
      runs-on: ubuntu-latest
      steps:
        - name: Run Tests
          run: echo "Running tests..."
