name: Simple Sequential Workflow

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - name: Build Project
          run: echo "Building the project..."

    test:
      runs-on: ubuntu-latest
      needs: build
      steps:
        - name: Run Tests
          run: echo "Running tests..."

    deploy:
      runs-on: ubuntu-latest
      needs: test
      steps:
        - name: Deploy Application
          run: echo "Deploying the application..."
